import { Negotiation, NegotiationStatus } from './types';

export const MOCK_NEGOTIATIONS: Negotiation[] = [
  {
    id: '1',
    title: 'AI導入コンサルティング',
    client: '株式会社テックフロンティア',
    date: '2023-10-05',
    description: '全社的なAI活用に向けた基盤構築の提案。先方のCTOは前向きだが、予算承認に時間がかかりそう。',
    amount: 5000000,
    status: '交渉中',
    nextActionDate: '2023-10-20',
    nextActionDetail: '予算修正案の提出',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '2',
    title: 'クラウドサーバー移行案件',
    client: 'グローバル商事',
    date: '2023-09-15',
    description: 'オンプレミスからの全面移行。競合他社と比較されている。',
    amount: 12000000,
    status: '提案中',
    nextActionDate: '2023-10-10',
    nextActionDetail: '技術デモンストレーション',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '3',
    title: 'セキュリティソフト年間契約',
    client: '山田建設',
    date: '2023-08-20',
    description: 'ランサムウェア対策としての導入。即決。',
    amount: 1500000,
    status: '受注',
    nextActionDate: '2023-09-01',
    nextActionDetail: '導入支援キックオフ',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '4',
    title: '社内チャットツール導入',
    client: '未来教育研究所',
    date: '2023-10-01',
    description: '無料プランからのアップグレード提案。',
    amount: 300000,
    status: '初回接触',
    nextActionDate: '2023-10-15',
    nextActionDetail: 'トライアルアカウント発行',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '5',
    title: 'ECサイトリニューアル',
    client: 'アパレルあおぞら',
    date: '2023-07-10',
    description: '予算感が合わず、今回は見送り。',
    amount: 8000000,
    status: '失注',
    nextActionDate: '2024-01-10',
    nextActionDetail: '半年後の状況伺い',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: '6',
    title: 'マーケティングオートメーション導入',
    client: '鈴木食品',
    date: '2023-10-12',
    description: 'Webサイトへの集客強化のため。',
    amount: 2500000,
    status: 'リード',
    nextActionDate: '2023-10-18',
    nextActionDetail: '初回ヒアリング',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const STATUS_COLORS: Record<NegotiationStatus, string> = {
  'リード': 'bg-gray-100 text-gray-800',
  '初回接触': 'bg-blue-100 text-blue-800',
  '提案中': 'bg-yellow-100 text-yellow-800',
  '交渉中': 'bg-purple-100 text-purple-800',
  '受注': 'bg-green-100 text-green-800',
  '失注': 'bg-red-100 text-red-800',
};